# Generated by Django 5.2.7 on 2025-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentemporal',
            name='codigo_udg',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_udg',
            field=models.CharField(help_text='Identificador único de la credencial', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_credencial',
            field=models.URLField(help_text='URL completa del QR de la credencial', unique=True),
        ),
    ]
