# Generated by Django 5.2.7 on 2025-10-05 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del perfil', upload_to='fotos_perfil/%Y/%m/')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (0 = primera foto)')),
                ('es_principal', models.BooleanField(default=False, help_text='Foto principal del perfil')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Biografía del usuario', max_length=500)),
                ('intereses', models.JSONField(default=list, help_text="Lista de intereses : ['deportes', 'música', 'cine', ...]")),
                ('distancia_maxima', models.IntegerField(default=50, help_text='Distancia máxima en km', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('edad_minima', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('edad_maxima', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('mostrar_edad', models.BooleanField(default=True)),
                ('mostrar_carrera', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
