# Generated by Django 5.2.7 on 2025-10-05 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_usuario2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='usuario_destino',
            field=models.ForeignKey(help_text='Usuario que recibe el swipe', on_delete=django.db.models.deletion.CASCADE, related_name='swipes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='usuario_origen',
            field=models.ForeignKey(help_text='Usuario que hace el swipe', on_delete=django.db.models.deletion.CASCADE, related_name='swipes_dados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['usuario1', 'usuario2'], name='matches_mat_usuario_ce2225_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['fecha'], name='matches_mat_fecha_7692dc_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['usuario_origen', 'tipo'], name='matches_swi_usuario_4c0e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['usuario_destino', 'tipo'], name='matches_swi_usuario_76274e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('usuario_origen', 'usuario_destino')},
        ),
    ]
