# Generated by Django 5.2.7 on 2025-10-05 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['match', 'fecha'], name='chat_mensaj_match_i_312380_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente', 'fecha'], name='chat_mensaj_remiten_9b92c0_idx'),
        ),
    ]
